name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["8.0", "8.1", "8.2"]

    name: php-lint (${{ matrix.php-versions }})
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Lint
        run: composer run lint

  php-cs-fixer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["8.1", "8.2"]

    name: php-cs
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        # Needs to run twice currently, to install cs-bin-dependency
        # https://github.com/bamarni/composer-bin-plugin/issues/72
        run: composer i && composer i

      - name: Run coding standards check
        run: composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )

  node:
    runs-on: ubuntu-latest

    name: eslint node
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Set up npm
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  stylelint:
    runs-on: ubuntu-latest

    name: stylelint node
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Set up npm
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run stylelint
